sudo: false
dist: trusty
language: java
jdk:
  - openjdk17

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.cache"

before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml
  - wget --no-check-certificate https://archive.apache.org/dist/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz
  - tar xzvf apache-maven-3.9.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.9.3/bin:$PATH
  - mvn -v
  - stty cols 80
  - google-chrome-stable --version
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d /usr/local/share/
    #- wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip -P ~/
    #  - unzip ~/chromedriver_linux64.zip -d ~/
    #  - rm ~/chromedriver_linux64.zip
  #  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  #  - wget https://bitbucket.org/anr-ru/docker-sources/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  #  - tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2
  #  - sudo rm -rf /usr/local/phantomjs
  #  - sudo mv phantomjs-2.1.1-linux-x86_64 /usr/local/phantomjs

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

jobs:
  include:
    - script: "mvn -P ci install -Dselenide.browser=Chrome"
    - stage: deploy
      provider: script
      script: "mvn -P ci deploy -DskipTests -Dselenide.browser=Chrome"
      on:
        tags: true
        branches: true
