sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"

before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml
  - stty cols 80
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-2.1.1-linux-x86_64 /usr/local/phantomjs

install:
  -  mvn -B -P ci install -Dphantomjs.binary.path=/usr/local/phantomjs/bin/phantomjs 

before_script:
  - chmod +x ./target/karma
  - chmod +x ./target/npm
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

deploy:
  provider: script
  script: "mvn -P ci deploy -Dphantomjs.binary.path=/usr/local/phantomjs/bin/phantomjs"
  skip_cleanup: false
  condition: "$TRAVIS_TAG = ^v.*$"
  on:
    tags: true
