sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
addons:
  firefox: "49.0"
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

before_script:
  - chmod +x ./target/karma
  - chmod +x ./target/bower
  - chmod +x ./target/npm

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    all_branches: true
