sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - stty cols 80
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-2.1.1-linux-x86_64 /usr/local/phantomjs

install:
  -  mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V 

before_script:
  - chmod +x ./target/karma
  - chmod +x ./target/bower
  - chmod +x ./target/npm
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    all_branches: true
